spring.application.name=springbootwebtutorial
spring.h2.console.enabled = true
spring.datasource.url=jdbc:h2:file:Users/Piyush/Project/tut_1
spring.datasource.username=piyushDB
spring.datasource.password=piyush123





